server:
  servlet:
    session:
      cookie:
        same-site: lax

spring:
  #spring
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  #data
  data:
    mongodb:
      host: ${DATA_MONGODB_HOST}
      port: ${DATA_MONGODB_PORT}
      database: ${DATA_MONGODB_DATABASE}
      authentication-database: ${DATA_MONGODB_AUTHENTICATIONDATABASE}
      username: ${DATA_MONGODB_USERNAME}
      password: ${DATA_MONGODB_PASSWORD}
      auto-index-creation: true

# 로깅 설정 추가
logging:
  level:
    org.springframework.data.mongodb: DEBUG  # MongoDB 쿼리 로그 활성화
    org.springframework.data: DEBUG         # Spring Data 전체 디버그 로그 (선택적)

#jwt
jwt:
  secret:
      key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_SECRET_EXPIRATIONTIME}
